----8. Giá bán của sản phẩm từ 500 đồng trở lên.---
ALTER TABLE SANPHAM 
ADD CONSTRAINT SANPHAM_GIA CHECK(GIA > 500)

----9. Mỗi lần mua hàng, khách hàng phải mua ít nhất 1 sản phẩm.
ALTER TABLE CTHD
ADD CONSTRAINT CHECK_SLMUA CHECK (SL>=1)
----10.Ngày khách hàng đăng ký là khách hàng thành viên phải lớn hơn ngày sinh của người đó.
ALTER TABLE KHACHHANG
ADD CONSTRAINT CHECK_NGAYDK CHECK(NGDK>NGSINH)
----11. Ngày mua hàng (NGHD) của một khách hàng thành viên sẽ lớn hơn hoặc bằng ngày khách hàng đó đăng ký thành viên (NGDK).----
CREATE TRIGGER UPDATE_KH
ON KHACHHANG
FOR UPDATE
AS
 DECLARE @NGDK SMALLDATETIME, @NGHD SMALLDATETIME

 SELECT @NGDK= NGDK
 FROM  INSERTED
 
 IF(@NGDK>ANY(SELECT NGHD
    FROM  HOADON A, INSERTED I
    WHERE A.MAKH=I.MAKH))
  BEGIN
   ROLLBACK TRAN
   PRINT 'ERROR!NGDK PHAI NHO HON NGHD'
  END
 ELSE
  PRINT' SUCCESSFUL'
------
CREATE TRIGGER HD
ON HOADON
FOR INSERT,UPDATE
AS
 DECLARE @NGDK SMALLDATETIME, 
   @NGHD SMALLDATETIME

 SELECT @NGDK=NGDK,@NGHD=NGHD
 FROM  INSERTED I, KHACHHANG A
 WHERE I.MAKH=A.MAKH

 IF @NGHD<@NGDK
  BEGIN
   ROLLBACK TRAN
   PRINT 'ERROR!NGHD PHAI LON HON NGDK'
  END
 ELSE
  PRINT' SUCCESSFUL'
 
 ----12. Ngày bán hàng (NGHD) của một nhân viên phải lớn hơn hoặc bằng ngày nhân viên đó vào làm.
CREATE TRIGGER UPDATE_NV_C12
ON NHANVIEN
FOR UPDATE
AS
 DECLARE @NGVL SMALLDATETIME, 
   @NGHD SMALLDATETIME

 SELECT @NGVL=NGVL
 FROM  INSERTED
 
 IF(@NGVL>ANY(SELECT NGHD
    FROM  HOADON A, INSERTED I
    WHERE A.MANV=I.MANV))
  BEGIN
   ROLLBACK TRAN
   PRINT 'ERROR!NGVL PHAI NHO HON NGHD'
  END
 ELSE
  PRINT' SUCCESSFUL'
 -------
CREATE TRIGGER HD_C12
ON HOADON
FOR INSERT,UPDATE
AS
 DECLARE @NGVL SMALLDATETIME, 
   @NGHD SMALLDATETIME

 SELECT @NGVL=NGVL,@NGHD=NGHD
 FROM  INSERTED I, NHANVIEN A
 WHERE I.MANV=A.MANV

 IF @NGHD<@NGVL
  BEGIN
   ROLLBACK TRAN
   PRINT 'ERROR!NGHD PHAI LON HON NGVL'
  END
 ELSE
  PRINT' SUCCESSFUL'

  ----13.Mỗi một hóa đơn phải có ít nhất một chi tiết hóa đơn.--------
CREATE TRIGGER CTHD_C13
ON CTHD
FOR DELETE,UPDATE
AS
 DECLARE @SL  INT,
   @SOHD INT

 SELECT @SL=COUNT(A.SOHD),@SOHD=D.SOHD
 FROM  DELETED D,CTHD A
 WHERE A.SOHD=D.SOHD
 GROUP BY  D.SOHD

 IF(@SL<1)
  BEGIN
   DELETE FROM HOADON
   WHERE  SOHD=@SOHD
   PRINT 'DA DELETE CTHD CUOI CUNG CUA HOADON TREN'
  END 
 ------
CREATE TRIGGER HOADON_C13
ON HOADON
FOR INSERT
AS
 DECLARE @SOHD INT

 SELECT @SOHD=SOHD
 FROM  INSERTED
 
 UPDATE CTHD
 SET  MASP='NONE',SL=0
 WHERE SOHD=@SOHD

 PRINT 'SUCCESSFUL! DE NGHI UPDATE LAI CTHD(MAC DINH:MASP="NONE", SL=0)'
 ----14.Trị giá của một hóa đơn là tổng thành tiền (số lượng*đơn giá) của các chi tiết thuộc hóa đơn đó.---
